version: '2'
services:
    'groceries-tesco':
        extends:
            file: docker-compose.yml
            service: groceries-tesco 
        command: >
          bash -c "
            make unit_tests && \
            make integration_tests && \
            make system_tests
          "
