package mocks

import domain "github.com/eggsbenjamin/groceries-tesco/domain"
import mock "github.com/stretchr/testify/mock"

// TescoClient is an autogenerated mock type for the TescoClient type
type TescoClient struct {
	mock.Mock
}

// GetProductsByGTIN provides a mock function with given fields: _a0
func (_m *TescoClient) GetProductsByGTIN(_a0 string) ([]*domain.Product, error) {
	ret := _m.Called(_a0)

	var r0 []*domain.Product
	if rf, ok := ret.Get(0).(func(string) []*domain.Product); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
